
blank_issues_enabled: false
contact_links:
  - name: Deployment or Implementation Question
    url: https://groups.google.com/a/fidoalliance.org/g/fido-dev
    about: Please use the FIDO-DEV list/group to ask questions about deployment and implementations